# Generated by Django 3.2 on 2021-04-23 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('status', models.CharField(max_length=20)),
                ('r_date', models.DateField(null=True)),
                ('d_date', models.DateField(null=True)),
                ('book', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
