# Generated by Django 3.2 on 2021-04-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_book_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(default='returned', max_length=100),
        ),
    ]
